# You can also use the 'cmd' parameter instead of free form format.
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: This command will change the working directory to somedir
    register: out
    shell: |
      id={{ item }}
      gnome_version=$(gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
      url="https://extensions.gnome.org/extension-info/?pk=${id}&shell_version=${gnome_version}"
      extension_info=$(curl $url -s)
      download_url_extension=$(echo $extension_info | grep -o -P '(?<="download_url": ").*(?="})')
      uuid=$(echo $extension_info | grep -o -P '(?<="uuid": ").*(?=", "name")')
      pretty_name=$(echo $extension_info | grep -o -P '(?<="name": ").*(?=", "creator")')
      download_url="https://extensions.gnome.org${download_url_extension}"
      echo $pretty_name 
      # wget -O ${uuid}.zip $download_url
      #     if ! gnome-extensions list | grep --quiet ${uuid}; then
      #     busctl --user call org.gnome.Shell.Extensions /org/gnome/Shell/Extensions org.gnome.Shell.Extensions InstallRemoteExtension s ${uuid}
      # fi
      # gnome-extensions enable ${uuid}
      # rm ${uuid}.zip
    args:
       executable: /usr/bin/expect
    loop:
      - 1
      - 2
  - debug: var=out.results