- hosts: localhost
  become: yes
  become_method: sudo
  pre_tasks:
  - name: Add non-standard package repositories and signing keys
    register: out
    shell: |
      apt install curl
      # Add tailscale package and keys
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      # Add syncthing package and keys
      curl -fsSL https://syncthing.net/release-key.gpg | sudo tee /usr/share/keyrings/syncthing-archive-keyring.gpg >/dev/null
      echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
      # add grub customizer ppa
      add-apt-repository ppa:danielrichter2007/grub-customizer -y
      # Install Flatpak
      apt install -Y flatpack
      apt install gnome-software-plugin-flatpak
      flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      # get gnome instal script
      wget -q https://raw.githubusercontent.com/TheTradeBakery/UbuntuDesktop/main/test_gnome_bash_script.sh && chmod +x test_gnome_bash_script.sh 
      wget -q https://github.com/TheTradeBakery/UbuntuDesktop/raw/main/mac_ish.sd.tar.gz
  - debug: var=out.stdout_lines
  - name: Run the equivalent of "apt-get update and upgrade" as a separate step
    apt:
      upgrade: yes
      update_cache: yes
  - name: Apt Package Installation
    apt:
      name:
        - gnome-shell-extension-manager
        - tailscale
        - syncthing
        - plank
        - lm-sensors
        - gnome-tweaks
        - grub-customizer
      state: latest
  - name: Snap Package Pycharm Installation
    community.general.snap:
      name: pycharm-community
      classic: true
  - name: Snap Package VSCode Installation
    community.general.snap:
      name: code
      classic: true
  - name: Other Snap Packages Installation
    community.general.snap:
      name: 
        - pynsource
  - name: Install .deb from internet
    ansible.builtin.apt:
      deb: https://veikk.com/image/catalog/Software/new/vktablet-1.2.3-1-x86_64.deb
      deb: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
  - name: Flatpack Package Installation
    community.general.flatpak:
      name:
      # photo
        - org.gimp.GIMP
        - com.boxy_svg.BoxySVG
        - io.github.lainsce.DotMatrix
        - org.gnome.Shotwell
      # office
        - org.libreoffice.LibreOffice
        - io.github.troyeguo.koodo-reader
      #productivity
        - net.daase.journable
        - com.rafaelmardojai.Blanket
      # music
        - com.spotify.Client
        - org.audacityteam.Audacity
      # video 
        - com.obsproject.Studio
        - com.github.unrud.VideoDownloader
        - org.kde.kdenlive
        - com.uploadedlobster.peek
      # internet 
        - com.google.Chrome
        - re.sonny.Tangram
      # security 
        - com.belmoussaoui.Authenticator
        - com.bitwarden.desktop
        - com.gitlab.davem.ClamTk
      # Other
        - com.github.rkoesters.xkcd-gtk
        - com.usebottles.bottles
      # utils
        - com.github.tchx84.Flatseal
        - io.github.vikdevelop.SaveDesktop
        - org.linux_hardware.hw-probe
        - com.github.donadigo.appeditor
        - io.gitlab.JakobDev.jdSimpleAutostart
        - io.github.jonmagon.kdiskmark
        - io.github.realmazharhussain.GdmSettings
        - com.github.bluesabre.darkbar
        - org.gnome.Logs
        - io.emeric.toolblex
        - com.github.ryonakano.pinit
        - page.codeberg.JakobDev.jdFlatpakSnapshot
      # tools
        - com.diy_fever.DIYLayoutCreator
        - com.github.phase1geo.minder
        - com.github.mdh34.quickdocs
        - de.lernsoftware_filius.Filius
        - io.dbeaver.DBeaverCommunity
        - org.fritzing.Fritzing
        - org.gaphor.Gaphor
        - com.jgraph.drawio.desktop
        - org.librepcb.LibrePCB
        - org.gnome.design.IconLibrary
        - org.gnome.baobab
        - re.sonny.Junction
        - org.raspberrypi.rpi-imager
      # database 
        - io.dbeaver.DBeaverCommunity
        - org.sqlitebrowser.sqlitebrowser
        - io.beekeeperstudio.Studio
      # programming tools
        - com.github.Murmele.Gittyup
        - com.github.arshubham.gitignore
        - com.github.treagod.spectator
        - re.sonny.Commit
      # programing ide
        - me.iepure.devtoolbox
        - org.gnome.meld
  - name: Add gnome-extensions
    register: out
    shell: |
      ./test_gnome_bash_script.sh {{ item }}
    loop:
      - 13   # Applications-menu
      - 19   # User Themes
      - 517  # Caffeine
      - 750  # Openweather
      - 779  # Clipboard
      - 841  # Freon (reltype of school gates went to learning styleies on lm_sensors, must run sensors-detect)
      - 906  # sound-output-device-chooseer
      - 989  # Syncthing
      - 1112 # Screenshot Tool
      - 1162 # emoji selector
      - 1401 # bluetooth quick connect
      - 1653 # Tweaks and Extensions in system menu
      - 3088 # Extensions 
      - 3396 # Color-picker
      - 3499 # Application-volume-mixer
      - 3763 # Battery Status (laptop battery) (% in setting menu)
      - 3991 # Bluetooth Battery
      - 4051 # Pi-Hole indicator
      - 4085 # Big Sur Status Area
      - 4198 # Dash-to-plank (Does Not Work on WAYLAND)
      - 4356 # Top Bar Organizer
      - 4408 # Colored Application Menu Icons
      - 4442 # gSnap (fancy zones)
      - 5112 # Tailscale-status
      - 5165 # Upower Battery
      - 5281 # Shutdown Button
  - debug: var=out.results
  - name: clean up gnome extension installs
    register: out
    shell: |
      rm -f test_gnome_bash_script.sh
      yes yes | sensors-detect
  - debug: var=out.stdout_lines
  - name: icons and user profile picture
    register: out
    shell: |
      # download and set user profile picture
      wget -q https://raw.githubusercontent.com/TheTradeBakery/UbuntuDesktop/main/ProfilePicture && chmod +x ProfilePicture
      localuser=$(eval getent passwd {$(awk '/^UID_MIN/ {print $2}' /etc/login.defs)..$(awk '/^UID_MAX/ {print $2}' /etc/login.defs)} | cut -d: -f1)
      mv ProfilePicture /var/lib/AccountsService/icons/$localuser
      # set icon back and theme
      wget -q https://raw.githubusercontent.com/TheTradeBakery/UbuntuDesktop/main/Icons.tar.xz && chmod +x Icons.tar.xz
      tar -xf Icons.tar.xz -C /usr/share/icons/ && rm -f Icons.tar.xz
      wget -q https://raw.githubusercontent.com/TheTradeBakery/UbuntuDesktop/main/Theme.tar.xz && chmod +x Theme.tar.xz
      tar -xf Theme.tar.xz -C /usr/share/themes/ && rm -f Theme.tar.xz
      flatpak override --filesystem=$HOME/.themes
      flatpak override --filesystem=$HOME/.icons
      flatpak override --env=GTK_THEME=WhiteSure-dark-solid
      flatpak override --env=ICON_THEME=WhiteSur-dark
    args:
      executable: /usr/bin/bash
  - debug: var=out.stdout_lines