- hosts: localhost
  become: yes
  become_method: sudo
  pre_tasks:
  - name: Add non-standard package repositories and signing keys
    register: out
    shell: |
      apt install curl
      # Add tailscale package and keys
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      # Add syncthing package and keys
      curl -fsSL https://syncthing.net/release-key.gpg | sudo tee /usr/share/keyrings/syncthing-archive-keyring.gpg >/dev/null
      echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
      # Install Flatpak
      apt install -Y flatpack
      apt install gnome-software-plugin-flatpak
      flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - debug: var=out.stdout_lines
  - name: Run the equivalent of "apt-get update and upgrade" as a separate step
    apt:
      upgrade: yes
      update_cache: yes
  - name: Apt Package Installation
    apt:
      name:
        - gnome-shell-extension-manager
        - tailscale
        - syncthing
        - plank
      state: latest
  - name: Snap Package Pycharm Installation
    community.general.snap:
      name: pycharm-community
      classic: true
  - name: Snap Package VSCode Installation
    community.general.snap:
      name: code
      classic: true
  - name: Other Snap Packages Installation
    community.general.snap:
      name: 
        - pynsource
  - name: Install .deb from internet
    ansible.builtin.apt:
      deb: https://veikk.com/image/catalog/Software/new/vktablet-1.2.3-1-x86_64.deb
      deb: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
  - name: Flatpack Package Installation
    community.general.flatpak:
      name:
      # photo
        - org.gimp.GIMP
        - com.boxy_svg.BoxySVG
        - io.github.lainsce.DotMatrix
        - org.gnome.Shotwell
      # office
        - org.libreoffice.LibreOffice
        - io.github.troyeguo.koodo-reader
      #productivity
        - net.daase.journable
        - com.rafaelmardojai.Blanket
      # music
        - com.spotify.Client
        - org.audacityteam.Audacity
      # video 
        - com.obsproject.Studio
        - com.github.unrud.VideoDownloader
        - org.kde.kdenlive
        - com.uploadedlobster.peek
      # internet 
        - com.google.Chrome
        - re.sonny.Tangram
      # security 
        - com.belmoussaoui.Authenticator
        - com.bitwarden.desktop
        - com.gitlab.davem.ClamTk
      # Other
        - com.github.rkoesters.xkcd-gtk
        - com.usebottles.bottles
      # utils
        - com.github.tchx84.Flatseal
        - io.github.vikdevelop.SaveDesktop
        - org.linux_hardware.hw-probe
        - com.github.donadigo.appeditor
        - io.gitlab.JakobDev.jdSimpleAutostart
        - io.github.jonmagon.kdiskmark
        - io.github.realmazharhussain.GdmSettings
        - com.github.bluesabre.darkbar
        - org.gnome.Logs
        - io.emeric.toolblex
        - com.github.ryonakano.pinit
        - page.codeberg.JakobDev.jdFlatpakSnapshot
      # tools
        - com.diy_fever.DIYLayoutCreator
        - com.github.phase1geo.minder
        - com.github.mdh34.quickdocs
        - de.lernsoftware_filius.Filius
        - io.dbeaver.DBeaverCommunity
        - org.fritzing.Fritzing
        - org.gaphor.Gaphor
        - com.jgraph.drawio.desktop
        - org.librepcb.LibrePCB
        - org.gnome.design.IconLibrary
        - org.gnome.baobab
        - re.sonny.Junction
      # database 
        - io.dbeaver.DBeaverCommunity
        - org.sqlitebrowser.sqlitebrowser
        - io.beekeeperstudio.Studio
      # programming tools
        - com.github.Murmele.Gittyup
        - com.github.arshubham.gitignore
        - com.github.treagod.spectator
        - re.sonny.Commit
      # programing ide
        - me.iepure.devtoolbox
        - org.gnome.meld
  roles:
    - role: luyz25.gnome_extensions
      vars:
        gnome_extension_ids:
        - id: 13   # Applications-menu
        - id: 19   # User Themes
        - id: 517  # Caffeine
        - id: 750  # Openweather
        - id: 779  # Clipboard
        - id: 841  # Freon (relies on lm_sensors, must run sensors-detect)
        - id: 906  # sound-output-device-chooseer
        - id: 989  # Syncthing
        - id: 1112 # Screenshot Tool
        - id: 1152 # emoji selector
        - id: 1401 # bluetooth quick connect
        - id: 1653 # Tweaks and Extensions in system menu
        - id: 3088 # Extensions 
        - id: 3396 # Color-picker
        - id: 3499 # Application-volume-mixer
        - id: 3763 # Battery Status (laptop battery) (% in setting menu)
        - id: 3991 # Bluetooth Battery
        - id: 4051 # Pi-Hole indicator
        - id: 4085 # Big Sur Status Area
        - id: 4198 # Dash-to-plank (Does Not Work on WAYLAND)
        - id: 4356 # Top Bar Organizer
        - id: 4408 # Colored Application Menu Icons
        - id: 4442 # gSnap (fancy zones)
        - id: 5112 # Tailscale-status
        - id: 5165 # Upower Battery
        - id: 5281 # Shutdown Button
